using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IconPack.Helper
{
    public static class FilenameToInfo
    {
        public static Dictionary<string, IItemInfo> perksInfo => new Dictionary<string, IItemInfo>()
        {
            { "iconPerks_buckleUp", new PerkInfo("Buckle Up", "Ashley J. Williams") },
            { "iconPerks_flipFlop", new PerkInfo("Flip-flop", "Ashley J. Williams") },
            { "iconPerks_mettleOfMan", new PerkInfo("Mettle of Man", "Ashley J. Williams") },
            { "iconPerks_aceInTheHole", new PerkInfo("Ace in the Hole", "Ace Visconti") },
            { "iconPerks_adrenaline", new PerkInfo("Adrenaline", "Meg Thomas") },
            { "iconPerks_aftercare", new PerkInfo("Aftercare", "Jeffrey \"Jeff\" Johansen") },
            { "iconPerks_agitation", new PerkInfo("Agitation", "The Trapper") },
            { "iconPerks_alert", new PerkInfo("Alert", "Feng Min") },
            { "iconPerks_aNursesCalling", new PerkInfo("A Nurse's Calling", "The Nurse") },
            { "iconPerks_anyMeansNecessary", new PerkInfo("Any Means Necessary", "Yui Kimura") },
            { "iconPerks_appraisal", new PerkInfo("Appraisal", "Élodie Rakoto") },
            { "iconPerks_autodidact", new PerkInfo("Autodidact", "Adam Francis") },
			{ "iconPerks_babySitter", new PerkInfo("Baby Sitter", "Steve Harrington") },
			{ "iconPerks_balancedLanding", new PerkInfo("Balanced Landing", "Nea Karlsson") },
			{ "iconPerks_bamboozle", new PerkInfo("Bamboozle", "The Clown") },
			{ "iconPerks_BBQAndChili", new PerkInfo("Barbecue & Chili", "The Cannibal") },
			{ "iconPerks_beastOfPrey", new PerkInfo("Beast of Prey", "The Huntress") },
			{ "iconPerks_betterTogether", new PerkInfo("Better Together ", "Nancy Wheeler") },
			{ "iconPerks_BiteTheBullet", new PerkInfo("Bite the Bullet", "Leon Scott Kennedy") },
			{ "iconPerks_bitterMurmur", new PerkInfo("Bitter Murmur", null) },
			{ "iconPerks_blastMine", new PerkInfo("Blast Mine", "Jill Valentine") },
			{ "iconPerks_bloodEcho", new PerkInfo("Blood Echo", "The Oni") },
			{ "iconPerks_bloodhound", new PerkInfo("Bloodhound", "The Wraith") },
			{ "iconPerks_bloodPact", new PerkInfo("Blood Pact", "Cheryl Mason") },
			{ "iconPerks_bloodWarden", new PerkInfo("Blood Warden", "The Nightmare") },
			{ "iconPerks_boilOver", new PerkInfo("Boil Over", "Kate Denson") },
			{ "iconPerks_bond", new PerkInfo("Bond", "Dwight Fairfield") },
			{ "iconPerks_BoonCircleOfHealing", new PerkInfo("Boon: Circle of Healing", "Mikaela Reid") },
			{ "iconPerks_BoonDestroyer", new PerkInfo("Shattered Hope", null) },
			{ "iconPerks_BoonShadowStep", new PerkInfo("Boon: Shadow Step", "Mikaela Reid") },
			{ "iconPerks_borrowedTime", new PerkInfo("Borrowed Time", "William \"Bill\" Overbeck") },
			{ "iconPerks_botanyKnowledge", new PerkInfo("Botany Knowledge", "Claudette Morel") },
			{ "iconPerks_breakdown", new PerkInfo("Breakdown", "Jeffrey \"Jeff\" Johansen") },
			{ "iconPerks_breakout", new PerkInfo("Breakout", "Yui Kimura") },
			{ "iconPerks_brutalStrength", new PerkInfo("Brutal Strength", "The Trapper") },
			{ "iconPerks_builtToLast", new PerkInfo("Built to Last", "Felix Richter") },
			{ "iconPerks_callOfBrine", new PerkInfo("Call of Brine", "The Onryō") },
			{ "iconPerks_calmSpirit", new PerkInfo("Calm Spirit", "Jake Park") },
			{ "iconPerks_camaraderie", new PerkInfo("Camaraderie", "Steve Harrington") },
			{ "iconPerks_Clairvoyance", new PerkInfo("Clairvoyance", "Mikaela Reid") },
			{ "iconPerks_corruptIntervention", new PerkInfo("Corrupt Intervention", "The Plague") },
			{ "iconPerks_coulrophobia", new PerkInfo("Coulrophobia", "The Clown") },
			{ "iconPerks_Counterforce", new PerkInfo("Counterforce", "Jill Valentine") },
			{ "iconPerks_coupDeGrace", new PerkInfo("Coup de Grâce", "The Twins") },
			{ "iconPerks_cruelConfinement", new PerkInfo("Claustrophobia", null) },
			{ "iconPerks_danceWithMe", new PerkInfo("Dance With Me", "Kate Denson") },
			{ "iconPerks_darkDevotion", new PerkInfo("Dark Devotion", "The Plague") },
			{ "iconPerks_DarknessRevelated", new PerkInfo("Darkness Revealed", "The Dredge") },
			{ "iconPerks_darkSense", new PerkInfo("Dark Sense", null) },
			{ "iconPerks_darkTheory", new PerkInfo("Boon: Dark Theory", "Yoichi Asakawa") },
			{ "iconPerks_DeadHard", new PerkInfo("Dead Hard", "David King") },
			{ "iconPerks_Deadlock", new PerkInfo("Deadlock", "The Cenobite") },
			{ "iconPerks_deadManSwitch", new PerkInfo("Dead Man's Switch", "The Deathslinger") },
			{ "iconPerks_deathbound", new PerkInfo("Deathbound", "The Executioner") },
			{ "iconPerks_deception", new PerkInfo("Deception", "Élodie Rakoto") },
			{ "iconPerks_decisiveStrike", new PerkInfo("Decisive Strike", "Laurie Strode") },
			{ "iconPerks_deerstalker", new PerkInfo("Deerstalker", null) },
			{ "iconPerks_dejaVu", new PerkInfo("Déjà vu", null) },
			{ "iconPerks_deliverance", new PerkInfo("Deliverance", "Adam Francis") },
			{ "iconPerks_desperateMeasures", new PerkInfo("Desperate Measures", "Felix Richter") },
			{ "iconPerks_detectivesHunch", new PerkInfo("Detective's Hunch", "Detective David Tapp") },
			{ "iconPerks_devourHope", new PerkInfo("Hex: Devour Hope", "The Hag") },
			{ "iconPerks_discordance", new PerkInfo("Discordance", "The Legion") },
			{ "iconPerks_Dissolution", new PerkInfo("Dissolution", "The Dredge") },
			{ "iconPerks_distortion", new PerkInfo("Distortion", "Jeffrey \"Jeff\" Johansen") },
			{ "iconPerks_distressing", new PerkInfo("Distressing", null) },
			{ "iconPerks_diversion", new PerkInfo("Diversion", "Adam Francis") },
			{ "iconPerks_dragonsGrip", new PerkInfo("Dragon's Grip", "The Blight") },
			{ "iconPerks_dyingLight", new PerkInfo("Dying Light", "The Shape") },
			{ "iconPerks_empathicConnection", new PerkInfo("Empathic connection", "Yoichi Asakawa") },
			{ "iconPerks_empathy", new PerkInfo("Empathy", "Claudette Morel") },
			{ "iconPerks_enduring", new PerkInfo("Enduring", "The Hillbilly") },
			{ "iconPerks_eruption", new PerkInfo("Eruption", "The Nemesis") },
			{ "iconPerks_FastTrack", new PerkInfo("Fast Track", "Yun-Jin Lee") },
			{ "iconPerks_fireUp", new PerkInfo("Fire Up", "The Nightmare") },
			{ "iconPerks_fixated", new PerkInfo("Fixated", "Nancy Wheeler") },
			{ "iconPerks_Flashbang", new PerkInfo("Flashbang", "Leon Scott Kennedy") },
			{ "iconPerks_floodOfRage", new PerkInfo("Scourge Hook: Floods of Rage", "The Onryō") },
			{ "iconPerks_forcedPenance", new PerkInfo("Forced Penance", "The Executioner") },
			{ "iconPerks_forThePeople", new PerkInfo("For The People", "Zarina Kassir") },
			{ "iconPerks_franklinsLoss", new PerkInfo("Franklin's Demise", "The Cannibal") },
			{ "iconPerks_furtiveChase", new PerkInfo("Furtive Chase", "The Ghost Face") },
			{ "iconPerks_gearHead", new PerkInfo("Gearhead", "The Deathslinger") },
			{ "iconPerks_generatorOvercharge", new PerkInfo("Overcharge", "The Doctor") },
			{ "iconPerks_guardian", new PerkInfo("Guardian", null) },
			{ "iconPerks_hangmansTrick", new PerkInfo("Hangman's Trick", "The Pig") },
			{ "iconPerks_hatred", new PerkInfo("Rancor", "The Spirit") },
			{ "iconPerks_hauntedGround", new PerkInfo("Hex: Haunted Ground", "The Spirit") },
			{ "iconPerks_headOn", new PerkInfo("Head On", "Jane Romero") },
			{ "iconPerks_hexBloodFavor", new PerkInfo("Hex: Blood Favour", "The Blight") },
			{ "iconPerks_HexCrowdControl", new PerkInfo("Hex: Crowd Control", "The Trickster") },
			{ "iconPerks_HexPlaything", new PerkInfo("Hex: Plaything", "The Cenobite") },
			{ "iconPerks_hexRetribution", new PerkInfo("Hex: Retribution", "The Deathslinger") },
			{ "iconPerks_hexUndying", new PerkInfo("Hex: Undying", "The Blight") },
			{ "iconPerks_Hoarder", new PerkInfo("Hoarder", "The Twins") },
			{ "iconPerks_hope", new PerkInfo("Hope", null) },
			{ "iconPerks_HuntressLullaby", new PerkInfo("Hex: Huntress Lullaby", "The Huntress") },
			{ "iconPerks_hysteria", new PerkInfo("Hysteria", "The Nemesis") },
			{ "iconPerks_imAllEars", new PerkInfo("I'm All Ears", "The Ghost Face") },
			{ "iconPerks_infectiousFright", new PerkInfo("Infectious Fright", "The Plague") },
			{ "iconPerks_InnerFocus", new PerkInfo("Inner Focus", "Haddie Kaur") },
			{ "iconPerks_innerStrength", new PerkInfo("Inner Strength", "Nancy Wheeler") },
			{ "iconPerks_insidious", new PerkInfo("Insidious", null) },
			{ "iconPerks_ironGrasp", new PerkInfo("Iron Grasp", null) },
			{ "iconPerks_ironMaiden", new PerkInfo("Iron Maiden", "The Legion") },
			{ "iconPerks_ironWill", new PerkInfo("Iron Will", "Jake Park") },
			{ "iconPerks_kindred", new PerkInfo("Kindred", null) },
			{ "iconPerks_knockOut", new PerkInfo("Knock Out", "The Cannibal") },
			{ "iconPerks_leader", new PerkInfo("Leader", "Dwight Fairfield") },
			{ "iconPerks_leftBehind", new PerkInfo("Left Behind", "William \"Bill\" Overbeck") },
			{ "iconPerks_lethalPursuer", new PerkInfo("Lethal Pursuer", "The Nemesis") },
			{ "iconPerks_lightborn", new PerkInfo("Lightborn", "The Hillbilly") },
			{ "iconPerks_lightweight", new PerkInfo("Lightweight", null) },
			{ "iconPerks_lithe", new PerkInfo("Lithe", "Feng Min") },
			{ "iconPerks_luckyBreak", new PerkInfo("Lucky Break", "Yui Kimura") },
			{ "iconPerks_madGrit", new PerkInfo("Mad Grit", "The Legion") },
			{ "iconPerks_makeYourChoice", new PerkInfo("Make Your Choice", "The Pig") },
			{ "iconPerks_mercilessStrom", new PerkInfo("Merciless storm", "The Onryō") },
			{ "iconPerks_mindBreaker", new PerkInfo("Fearmonger", null) },
			{ "iconPerks_monitorAndAbuse", new PerkInfo("Monitor & Abuse", "The Doctor") },
			{ "iconPerks_monstrousShrine", new PerkInfo("Monstrous Shrine", null) },
			{ "iconPerks_nemesis", new PerkInfo("Nemesis", "The Oni") },
			{ "iconPerks_NoMither", new PerkInfo("No Mither", "David King") },
			{ "iconPerks_noOneEscapesDeath", new PerkInfo("Hex: No One Escapes Death", null) },
			{ "iconPerks_noOneLeftBehind", new PerkInfo("No One Left Behind", null) },
			{ "iconPerks_NoWayOut", new PerkInfo("No Way Out", "The Trickster") },
			{ "iconPerks_objectOfObsession", new PerkInfo("Object of Obsession", "Laurie Strode") },
			{ "iconPerks_offTheRecord", new PerkInfo("Off the Record", "Zarina Kassir") },
			{ "iconPerks_openHanded", new PerkInfo("Open-Handed", "Ace Visconti") },
			{ "iconPerks_Oppression", new PerkInfo("Oppression", "The Twins") },
			{ "iconPerks_overwelmingPresence", new PerkInfo("Overwelming Presence", "The Doctor") },
			{ "iconPerks_Overzealous", new PerkInfo("Overzealous", "Haddie Kaur") },
			{ "iconPerks_parentalGuidance", new PerkInfo("Parental Guidance", "Yoichi Asakawa") },
			{ "iconPerks_pharmacy", new PerkInfo("Pharmacy", "Quentin Smith") },
			{ "iconPerks_playWithYourFood", new PerkInfo("Play with Your Food", "The Shape") },
			{ "iconPerks_plunderersInstinct", new PerkInfo("Plunderer's Instinct", null) },
			{ "iconPerks_poised", new PerkInfo("Poised", "Jane Romero") },
			{ "iconPerks_popGoesTheWeasel", new PerkInfo("Pop Goes the Weasel", "The Clown") },
			{ "IconPerks_powerStruggle", new PerkInfo("Power Struggle", "Élodie Rakoto") },
			{ "iconPerks_predator", new PerkInfo("Predator", "The Wraith") },
			{ "iconPerks_premonition", new PerkInfo("Premonition", null) },
			{ "iconPerks_proveThyself", new PerkInfo("Prove Thyself", "Dwight Fairfield") },
			{ "iconPerks_pushThroughIt", new PerkInfo("Renewal", null) },
			{ "iconPerks_quickAndQuiet", new PerkInfo("Quick & Quite", "Meg Thomas") },
			{ "iconPerks_redHerring", new PerkInfo("Red Herring", "Zarina Kassir") },
			{ "iconPerks_rememberMe", new PerkInfo("Remember Me", "The Nightmare") },
			{ "iconPerks_repressedAlliance", new PerkInfo("Repressed Alliance", "Cheryl Mason") },
			{ "iconPerks_ResidualManifest", new PerkInfo("Residual Manifest", "Haddie Kaur") },
			{ "iconPerks_resilience", new PerkInfo("Resilience", null) },
			{ "iconPerks_Resurgence", new PerkInfo("Resurgence", "Jill Valentine") },
			{ "iconPerks_RookieSpirit", new PerkInfo("Rookie Spirit", "Leon Scott Kennedy") },
			{ "iconPerks_ruin", new PerkInfo("Hex: Ruin", "The Hag") },
			{ "iconPerks_saboteur", new PerkInfo("Saboteur", "Jake Park") },
			{ "iconPerks_saveTheBestForLast", new PerkInfo("Save the Best for Last", "The Shape") },
			{ "iconPerks_ScourgeHookGiftOfPain", new PerkInfo("Scourge Hook: Gift of Pain", "The Cenobite") },
			{ "iconPerks_secondWind", new PerkInfo("Second Wind", "Steve Harrington") },
			{ "iconPerks_selfCare", new PerkInfo("Self Care", "Claudette Morel") },
			{ "iconPerks_Self-Preservation", new PerkInfo("Self-Preservation", "Yun-Jin Lee") },
			{ "iconPerks_SepticTouch", new PerkInfo("Septic Touch", "The Dredge") },
			{ "iconPerks_shadowborn", new PerkInfo("Shadowborn", "The Wraith") },
			{ "iconPerks_situationalAwareness", new PerkInfo("Situational Awareness", null) },
			{ "iconPerks_slipperyMeat", new PerkInfo("Slippery Meat", null) },
			{ "iconPerks_sloppyButcher", new PerkInfo("Sloppy Butcher", null) },
			{ "iconPerks_smallGame", new PerkInfo("Small Game", null) },
			{ "iconPerks_SmashHit", new PerkInfo("Smash Hit", "Yun-Jin Lee") },
			{ "iconPerks_soleSurvivor", new PerkInfo("Sole Survivor", "Laurie Strode") },
			{ "iconPerks_solidarity", new PerkInfo("Solidarity", "Jane Romero") },
			{ "iconPerks_soulGuard", new PerkInfo("Soul Guard", "Cheryl Mason") },
			{ "iconPerks_spiesFromTheShadows", new PerkInfo("Spies from the Shadows", null) },
			{ "iconPerks_spineChill", new PerkInfo("Spine Chill", null) },
			{ "iconPerks_spiritFury", new PerkInfo("Spirit Fury", "The Spirit") },
			{ "iconPerks_sprintBurst", new PerkInfo("Sprint Burst", "Meg Thomas") },
			{ "iconPerks_stakeOut", new PerkInfo("Stake Out", "Detective David Tapp") },
			{ "iconPerks_Starstruck", new PerkInfo("Starstruck", "The Trickster") },
			{ "iconPerks_streetwise", new PerkInfo("Streetwise", "Nea Karlsson") },
			{ "iconPerks_stridor", new PerkInfo("Stridor", "The Nurse") },
			{ "iconPerks_surge", new PerkInfo("Jolt", null) },
			{ "iconPerks_surveillance", new PerkInfo("Surveillance", "The Pig") },
			{ "iconPerks_survivalInstincts", new PerkInfo("Inner Healing", null) },
			{ "iconPerks_technician", new PerkInfo("Technician", "Feng Min") },
			{ "iconPerks_tenacity", new PerkInfo("Tenacity", "Detective David Tapp") },
			{ "iconPerks_TerritorialImperative", new PerkInfo("Territorial Imperative", "The Huntress") },
			{ "iconPerks_thatanophobia", new PerkInfo("Thatanophobia", "The Nurse") },
			{ "iconPerks_theThirdSeal", new PerkInfo("Hex: The Third Seal", "The Hag") },
			{ "iconPerks_thisIsNotHappening", new PerkInfo("This is not Happening", null) },
			{ "iconPerks_thrillingTremors", new PerkInfo("Thrilling Tremors", "The Ghost Face") },
			{ "iconPerks_thrillOfTheHunt", new PerkInfo("Hex: Thrill of the Hunt", null) },
			{ "iconPerks_tinkerer", new PerkInfo("Tinkerer", "The Hillbilly") },
			{ "iconPerks_trailOfTorment", new PerkInfo("Trail of Torment", "The Executioner") },
			{ "iconPerks_unbreakable", new PerkInfo("Unbreakable", "William \"Bill\" Overbeck") },
			{ "iconPerks_unnervingPresence", new PerkInfo("Unnerving presence", "The Trapper") },
			{ "iconPerks_unrelenting", new PerkInfo("Unrelenting", null) },
			{ "iconPerks_upTheAnte", new PerkInfo("Up the Ante", "Ace Visconti") },
			{ "iconPerks_urbanEvasion", new PerkInfo("Urban Evasion", "Nea Karlsson") },
			{ "iconPerks_vigil", new PerkInfo("Vigil", "Quentin Smith") },
			{ "iconPerks_visionary", new PerkInfo("Visionary", "Felix Richter") },
			{ "iconPerks_wakeUp", new PerkInfo("Wake Up", "Quentin Smith") },
			{ "iconPerks_wellMakeIt", new PerkInfo("We'll Make it", null) },
			{ "iconPerks_WereGonnaLiveForever", new PerkInfo("We're Gonna Live Forever", "David King") },
			{ "iconPerks_whispers", new PerkInfo("Whispers", null) },
			{ "iconPerks_windowsOfOpportunity", new PerkInfo("Windows of Opportunity", "Kate Denson") },
			{ "iconPerks_zanshinTactics", new PerkInfo("Zanshin Tactics", "The Oni") },
			{ "T_iconPerks_BoonExponential", new PerkInfo("Boon: Exponential", "Jonah Vasquez") },
			{ "T_iconPerks_CorrectiveAction", new PerkInfo("Corrective Action", "Jonah Vasquez") },
			{ "T_iconPerks_grimEmbrace", new PerkInfo("Grim embrace", "The Artist") },
			{ "T_iconPerks_hexPentimento", new PerkInfo("Hex: Pentimento", "The Artist") },
			{ "T_iconPerks_Overcome", new PerkInfo("Overcome", "Jonah Vasquez") },
			{ "T_iconPerks_painResonance", new PerkInfo("Scourge Hook: Pain Resonance", "The Artist") }
		};

		public static Dictionary<string, string> portraitsInfo = new Dictionary<string, string>()
		{
			{"AF_charSelect_portrait", "Adam Francis" },
			{"AV_charSelect_portrait", "Ace Visconti" },
			{"BE_charSelect_portrait", "The Huntress" },
			{"BO_charSelect_portrait", "William \"Bill\" Overbeck" },
			{"CA_charSelect_portrait", "The Cannibal" },
			{"CM_charSelect_portrait", "Claudette Morel" },
			{"DF_charSelect_portrait", "Dwight Fairfield" },
			{"DK_charSelect_portrait", "David King" },
			{"DO_charSelect_portrait", "The Doctor" },
			{"FK_charSelect_portrait", "The Pig" },
			{"FM_charSelect_portrait", "Feng Min" },
			{"FS_charSelect_portrait", "Detective David Tapp" },
			{"GK_charSelect_portrait", "The Clown" },
			{"GS_charSelect_portrait", "Kate Denson" },
			{"HA_charSelect_portrait", "The Hag" },
			{"HB_charSelect_portrait", "The Hillbilly" },
			{"HK_charSelect_portrait", "The Spirit" },
			{"JP_charSelect_portrait", "Jake Park" },
			{"K20_charSelect_portrait", "The Executioner" },
			{"K21_charSelect_portrait", "The Blight" },
			{"K22_charSelect_portrait", "The Twins" },
			{"K23_charSelect_portrait", "The Trickster" },
			{"K24_charSelect_portrait", "The Nemesis" },
			{"K25_charSelect_portrait", "The Cenobite" },
			{"K27_charSelect_portrait", "The Onryō" },
			{"K28_charSelect_portrait", "The Dredge" },
			{"KK_charSelect_portrait", "The Legion" },
			{"KS_charSelect_portrait", "Jeffrey \"Jeff\" Johansen" },
			{"LS_charSelect_portrait", "Laurie Strode" },
			{"MK_charSelect_portrait", "The Plague" },
			{"MS_charSelect_portrait", "Jane Romero" },
			{"MS2_charSelect_portrait", "Ashley J. Williams" },
			{"MT_charSelect_portrait", "Meg Thomas" },
			{"NK_charSelect_portrait", "Nea Karlsson" },
			{"NR_charSelect_portrait", "The Nurse" },
			{"OK_charSelect_portrait", "The Ghost Face" },
			{"QF_charSelect_portrait", "Nancy Wheeler" },
			{"QK_charSelect_portrait", "The Demogorgon" },
			{"QM_charSelect_portrait", "Steve Harrington" },
			{"QS_charSelect_portrait", "Quentin Smith" },
			{"S22_charSelect_portrait", "Cheryl Mason" },
			{"S22J_charSelect_portrait", "James Sunderland" },
			{"S23_charSelect_portrait", "Felix Richter" },
			{"S24_charSelect_portrait", "Élodie Rakoto" },
			{"S25_charSelect_portrait", "Yun-Jin Lee" },
			{"S26_charSelect_portrait", "Jill Valentine" },
			{"S27_charSelect_portrait", "Leon Scott Kennedy" },
			{"S28_charSelect_portrait", "Mikaela Reid" },
			{"S30_charSelect_portrait", "Yoichi Asakawa" },
			{"S31_charSelect_portrait", "Haddie Kaur" },
			{"SD_charSelect_portrait", "The Nightmare" },
			{"SH_charSelect_portrait", "The Shape" },
			{"SK_charSelect_portrait", "The Oni" },
			{"SS_charSelect_portrait", "Yui Kimura" },
			{"T_K26_charSelect_portrait", "The Artist" },
			{"T_S29_charSelect_portrait", "Jonah Vasquez" },
			{"TR_charSelect_portrait", "The Trapper" },
			{"UK_charSelect_portrait", "The Deathslinger" },
			{"US_charSelect_portrait", "Zarina Kassir" },
			{"WR_charSelect_portrait", "The Wraith" }
		};

		public static Dictionary<string, string> survivorItemInfo = new Dictionary<string, string>()
		{
			{"iconItems_flashlight_anniversary2020", "Anniversary Flashlight" },
			{"iconItems_flashlight_anniversary2022", "Masquerade Flashlight" },
			{"iconItems_medkit_anniversary2020", "Anniversary Med-Kit" },
			{"iconItems_medkit_anniversary2022", "Masquerade Med-Kit" },
			{"iconItems_partyPopper", "Third Year Party Starter" },
			{"iconItems_toolbox_anniversary2021", "Anniversary Toolbox" },
			{"iconItems_toolbox_anniversary2022", "Masquerade Toolbox" },
			{"iconItems_flashlightHalloween", "Will O' Wisp" },
			{"iconItems_medkitHalloween", "All Hallows' Eve Lunchbox" },
			{"iconItems_LimitedFragileMirror", "Pocket Mirror" },
			{"iconItems_LimitedItemVaccine", "Vaccine" },
			{"iconItems_LimitedLamentConfiguration", "Lament Configuration" },
			{"iconItems_LimitedRepairedMirror", "Pocket Mirror" },
			{"iconItems_LimitedVhsTape", "VHS Tape" },
			{"iconItems_flashbangGrenade", "Flash Granade" },
			{"iconItems_toolboxLunar", "Festive Toolbox" },
			{"iconItems_winterEventFirecracker", "Winter Party Starter" },
			{"iconItems_brokenKey", "Broken Key" },
			{"iconItems_chineseFirecracker", "Chinese Firecracker" },
			{"iconItems_dullKey", "Dull Key" },
			{"iconItems_firstAidKit", "First Aid Kit" },
			{"iconItems_flashlight", "Flashlight" },
			{"iconItems_flashlightSport", "Sport Flashlight" },
			{"iconItems_flashlightUtility", "Utility Flashlight" },
			{"iconItems_key", "Skeleton Key" },
			{"iconItems_map", "Map" },
			{"iconItems_medkit", "Emergency Med-Kit" },
			{"iconItems_rainbowMap", "Rainbow Map" },
			{"iconItems_rangersAidKit", "Ranger Med-Kit" },
			{"iconItems_rundownAidKit", "Camping Aid Kit" },
			{"iconItems_toolbox", "Toolbox" },
			{"iconItems_toolboxAlexs", "Alex's Toolbox" },
			{"iconItems_toolboxCommodious", "Commodious Toolbox" },
			{"iconItems_toolboxEngineers", "Engineer's Toolbox" },
			{"iconItems_toolboxMechanics", "Mechanic's Toolbox" },
			{"iconItems_toolboxWornOut", "Worn-Out Tools" }
		};

		public static Dictionary<string, IItemInfo> killerPowerInfo = new Dictionary<string, IItemInfo>()
		{
			{"iconPowers_axe", new KillerPowerInfo("Hunting Hatchets", "The Huntress") },
			{"iconPowers_bell", new KillerPowerInfo("Wailing Bell", "The Wraith") },
			{"iconPowers_blackenedCatalyst", new KillerPowerInfo("Blackened Catalyst", "The Hag") },
			{"iconPowers_bloodBond_01", new KillerPowerInfo("Blood Bond: Charlotte", "The Twins") },
			{"iconPowers_bloodBond_02", new KillerPowerInfo("Blood Bond: Victor", "The Twins") },
			{"iconPowers_breath", new KillerPowerInfo("Spencer's Last Breath", "The Nurse") },
			{"iconPowers_bubbasChainsaw", new KillerPowerInfo("Bubba's Chainsaw", "The Cannibal") },
			{"iconPowers_cartersSpark", new KillerPowerInfo("Carter's Spark", "The Doctor") },
			{"iconPowers_chainsaw", new KillerPowerInfo("Chainsaw", "The Hillbilly") },
			{"iconPowers_delugeOfFear", new KillerPowerInfo("Deluge of Fear", "The Onryō") },
			{"iconPowers_delugeOfFear2", new KillerPowerInfo("Deluge of Fear: Manifested", "The Onryō") },
			{"iconPowers_detention", new KillerPowerInfo("Detention", "The Teacher") },
			{"iconPowers_dreamMaster", new KillerPowerInfo("Dream Demon", "The Nightmare") },
			{"iconPowers_feralFrenzy", new KillerPowerInfo("Feral Frenzy", "The Legion") },
			{"iconPowers_gasBomb", new KillerPowerInfo("The Afterpiece Tonic", "The Clown") },
			{"iconPowers_gasBomb2", new KillerPowerInfo("The Afterpiece Tonic: Antidote", "The Clown") },
			{"iconPowers_ghostPower_activated", new KillerPowerInfo("Night Shroud: Activated", "The Ghost Face") },
			{"iconPowers_ghostPower_available", new KillerPowerInfo("Night Shroud", "The Ghost Face") },
			{"iconPowers_huntingHatchets", new KillerPowerInfo("Hunting Hatchets", "The Huntress") },
			{"iconPowers_K21", new KillerPowerInfo("Blighted Corruption", "The Blight") },
			{"iconPowers_ofTheAbyss", new KillerPowerInfo("Of the Abyss", "The Demogorgon") },
			{"iconPowers_reverseBearTrap", new KillerPowerInfo("Jigsaw's Baptism", "The Pig") },
			{"iconPowers_Showstopper_01", new KillerPowerInfo("Showstopper", "The Trickster") },
			{"iconPowers_Showstopper_02", new KillerPowerInfo("Showstopper: The Main Event", "The Trickster") },
			{"iconPowers_Showstopper_03", new KillerPowerInfo("Showstopper: No Blade", "The Trickster") },
			{"iconPowers_stalker1", new KillerPowerInfo("Evil Within I", "The Shape") },
			{"iconPowers_stalker2", new KillerPowerInfo("Evil Within II", "The Shape") },
			{"iconPowers_stalker3", new KillerPowerInfo("Evil Within III", "The Shape") },
			{"iconPowers_stalker3a", new KillerPowerInfo("Evil Within III", "The Shape") },
			{"iconPowers_summonsOfPain", new KillerPowerInfo("Summons of Pain", "The Cenobite") },
			{"iconPowers_Tantrum", new KillerPowerInfo("Chainsaw Sweep", "The Cannibal") },
			{"iconPowers_trap", new KillerPowerInfo("Bear Trap", "The Trapper") },
			{"iconPowers_T-virus1", new KillerPowerInfo("T-VIRUS MUTATION RATE 1", "The Nemesis") },
			{"iconPowers_T-virus2", new KillerPowerInfo("T-VIRUS MUTATION RATE 2", "The Nemesis") },
			{"iconPowers_T-virus3", new KillerPowerInfo("T-VIRUS MUTATION RATE 3", "The Nemesis") },
			{"iconPowers_UK", new KillerPowerInfo("The Redeemer", "The Deathslinger") },
			{"iconPowers_UK_chainBreak", new KillerPowerInfo("The Redeemer", "The Deathslinger") },
			{"iconPowers_vilePurge", new KillerPowerInfo("Vile Purge", "The Plague") },
			{"iconPowers_Wales_ritesOfJudgement", new KillerPowerInfo("Rites of Judgement", "The Executioner") },
			{"iconPowers_yamaokasHaunting", new KillerPowerInfo("Yamaoka's Haunting", "The Spirit") },
			{"iconPowers_yamaokasWrath", new KillerPowerInfo("Yamaoka's Wrath", "The Oni") },
			{"iconPowers_yamaokasWrath_demon", new KillerPowerInfo("Yamaoka's Wrath: Blood Fury", "The Oni") },
			{"T_iconPowers_birdsOfTorment", new KillerPowerInfo("Birds of Torment", "The Artist") },
			{"T_iconPowers_ReignofDarkness", new KillerPowerInfo("Reign of Darkness", "The Dredge") }
		};

		public static Dictionary<string, IItemInfo> survivorItemAddonsInfo = new Dictionary<string, IItemInfo>()
		{
			//Survivor item add-ons
			{"iconAddon_brokenFlashlightBulb", new AddOnsInfo("Broken Bulb", "Flashlight") },
			{"iconAddon_battery", new AddOnsInfo("Battery", "Flashlight") },
			{"iconAddon_focusLens", new AddOnsInfo("Focus Lens", "Flashlight") },
			{"iconAddon_heavyDutyBattery", new AddOnsInfo("Heavy Duty Battery", "Flashlight") },
			{"iconAddon_highEndSapphireLens", new AddOnsInfo("High-End Sapphire Lens", "Flashlight") },
			{"iconAddon_intenseHalogen", new AddOnsInfo("Intense Halogen", "Flashlight") },
			{"iconAddon_leatherGrip", new AddOnsInfo("Leather Grip", "Flashlight") },
			{"iconAddon_longLifeBattery", new AddOnsInfo("Long Life Battery", "Flashlight") },
			{"iconAddon_oddBulb", new AddOnsInfo("Odd Bulb", "Flashlight") },
			{"iconAddon_powerBulb", new AddOnsInfo("Power Bulb", "Flashlight") },
			{"iconAddon_rubberGrip", new AddOnsInfo("Rubber Grip", "Flashlight") },
			{"iconAddon_threadedFilament", new AddOnsInfo("Low Amp Filament", "Flashlight") },
			{"iconAddon_tirOptic", new AddOnsInfo("TIR Optic", "Flashlight") },
			{"iconAddon_wideLens", new AddOnsInfo("Wide Lens", "Flashlight") },
			{"iconAddon_bloodAmber", new AddOnsInfo("Blood Amber", "Key") },
			{"iconAddon_milkyGlass", new AddOnsInfo("Milky Glass", "Key") },
			{"iconAddon_prayerBeads", new AddOnsInfo("Prayer Beads", "Key") },
			{"iconAddon_prayerRope", new AddOnsInfo("Prayer Rope", "Key") },
			{"iconAddon_scratchedPearl", new AddOnsInfo("Scratched Pearl", "Key") },
			{"iconAddon_tokenErroded", new AddOnsInfo("Eroded Token", "Key") },
			{"iconAddon_tokenGold", new AddOnsInfo("Gold Token", "Key") },
			{"iconAddon_uniqueRing", new AddOnsInfo("Unique Wedding Ring", "Key") },
			{"iconAddon_weavedRing", new AddOnsInfo("Weaved Ring", "Key") },
			{"iconAddon_beadCrystal", new AddOnsInfo("Crystal Bead", "Map") },
			{"iconAddon_beadGlass", new AddOnsInfo("Glass Bead", "Map") },
			{"iconAddon_mapAddendum", new AddOnsInfo("Map Addendum", "Map") },
			{"iconAddon_retardantJelly", new AddOnsInfo("Retardant Jelly", "Map") },
			{"iconAddon_ropeBlack", new AddOnsInfo("Black Silk Cord", "Map") },
			{"iconAddon_ropeRed", new AddOnsInfo("Red Twine", "Map") },
			{"iconAddon_ropeYellow", new AddOnsInfo("Yellow Wire", "Map") },
			{"iconAddon_stampOdd", new AddOnsInfo("Odd Stamp", "Map") },
			{"iconAddon_stampUnusual", new AddOnsInfo("Unusual Stamp", "Map") },
			{"iconAddon_blightedSyringe", new AddOnsInfo("Refined Serum", "Med-Kit") },
			{"iconAddon_abdominalDressing", new AddOnsInfo("Abdominal Dressing", "Med-Kit") },
			{"iconAddon_bandages", new AddOnsInfo("Bandages", "Med-Kit") },
			{"iconAddon_butterflyTape", new AddOnsInfo("Butterfly Tape", "Med-Kit") },
			{"iconAddon_gauseRoll", new AddOnsInfo("Gauze Roll", "Med-Kit") },
			{"iconAddon_gelDressings", new AddOnsInfo("Gel Dressings", "Med-Kit") },
			{"iconAddon_gloves", new AddOnsInfo("Rubber Gloves", "Med-Kit") },
			{"iconAddon_needAndThread", new AddOnsInfo("Needle & Thread", "Med-Kit") },
			{"iconAddon_scissors", new AddOnsInfo("Medical Scissors", "Med-Kit") },
			{"iconAddon_selfAdherentWrap", new AddOnsInfo("Self Adherent Wrap", "Med-Kit") },
			{"iconAddon_sponge", new AddOnsInfo("Sponge", "Med-Kit") },
			{"iconAddon_spoolOfWire", new AddOnsInfo("Wire Spool", "Med-Kit") },
			{"iconAddon_springClamp", new AddOnsInfo("Spring Clamp", "Med-Kit") },
			{"iconAddon_stypticAgent", new AddOnsInfo("Styptic Agent", "Med-Kit") },
			{"iconAddon_surgicalSuture", new AddOnsInfo("Surgical Suture", "Med-Kit") },
			{"iconAddon_syringe", new AddOnsInfo("Anti-Haemorrhagic Syringe", "Med-Kit") },
			{"iconAddon_brandNewPart", new AddOnsInfo("Brand New Part", "Toolbox") },
			{"iconAddon_cleanRag", new AddOnsInfo("Clean Rag", "Toolbox") },
			{"iconAddon_cuttingWire", new AddOnsInfo("Cutting Wire", "Toolbox") },
			{"iconAddon_gripWrench", new AddOnsInfo("Grip Wrench", "Toolbox") },
			{"iconAddon_instructions", new AddOnsInfo("Instructions", "Toolbox") },
			{"iconAddon_metalSaw", new AddOnsInfo("Hacksaw", "Toolbox") },
			{"iconAddon_protectiveGloves", new AddOnsInfo("Protective Gloves", "Toolbox") },
			{"iconAddon_scraps", new AddOnsInfo("Scraps", "Toolbox") },
			{"iconAddon_socketSwivels", new AddOnsInfo("Socket Swivels", "Toolbox") }
		};

		public static Dictionary<string, IItemInfo> killerItemAddonsInfo = new Dictionary<string, IItemInfo>()
		{
			{"Aurora/iconAddon_babyTeeth", new AddOnsInfo("Baby Teeth", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_bloodiedBlackHood", new AddOnsInfo("Bloody Black Hood", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_catFigurine", new AddOnsInfo("Cat Figurine", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_catsEye", new AddOnsInfo("Cat's Eye", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_ceremonialCandelabrum", new AddOnsInfo("Ceremonial Candelabrum", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_dropOfPerfume", new AddOnsInfo("Drop of Perfume", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_forestStew", new AddOnsInfo("Forest Stew", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_iridescentPendant", new AddOnsInfo("Iridescent Pendant", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_madeleinesGlove", new AddOnsInfo("Madeleine's Glove", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_madeleinesScarf", new AddOnsInfo("Madeleine's Scarf", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_rustedNeedle", new AddOnsInfo("Rusted Needle", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_sewerSludge", new AddOnsInfo("Sewer Sludge", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_silencingCloth", new AddOnsInfo("Silencing Cloth", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_souredMilk", new AddOnsInfo("Soured Milk", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_spinningTop", new AddOnsInfo("Spinning Top", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_staleBiscuit", new AddOnsInfo("Stale Biscuit", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_tinyFingernail", new AddOnsInfo("Tiny Fingernail", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_toySword", new AddOnsInfo("Toy Sword", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_victorsSoldier", new AddOnsInfo("Victor's Soldier", "Blood Bond", "The Twins") },
			{"Aurora/iconAddon_weightyRattle", new AddOnsInfo("Weighty Rattle", "Blood Bond", "The Twins") },
			{"Cannibal/iconAddon_awardwinningChili", new AddOnsInfo("Award-winning Chilli", "Bubba's Chainsaw", "The Cannibal") },
			{"Cannibal/iconAddon_chili", new AddOnsInfo("Chilli", "Bubba's Chainsaw", "The Cannibal") },
			{"Cannibal/iconAddon_iridescentFlesh", new AddOnsInfo("Iridescent Flesh", "Bubba's Chainsaw", "The Cannibal") },
			{"Cannibal/iconAddon_knifeScratches", new AddOnsInfo("Knife Scratches", "Bubba's Chainsaw", "The Cannibal") },
			{"Cannibal/iconAddon_theBeastsMark", new AddOnsInfo("The Beast's Marks", "Bubba's Chainsaw", "The Cannibal") },
			{"Cannibal/iconAddon_theGrease", new AddOnsInfo("The Grease", "Bubba's Chainsaw", "The Cannibal") },
			{"Comet/icons_Addon_BloodyBoa", new AddOnsInfo("Bloody Boa", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_CagedHeartShoes", new AddOnsInfo("Caged Heart Shoes", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_CutThruUsingle", new AddOnsInfo("Cut Thru U Single", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_DeathThroesCompilation", new AddOnsInfo("Death Throes Compilation", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_DiamondCufflinks", new AddOnsInfo("Diamond Cufflinks", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_EdgeOfRevivalAlbum", new AddOnsInfo("Edge of Revival Album", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_FizzSpinSoda", new AddOnsInfo("Fizz-Spin Soda", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_InfernoWires", new AddOnsInfo("Inferno Wires", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_IridescentPhotocard", new AddOnsInfo("Iridescent Photocard", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_JiWoonsAutograph", new AddOnsInfo("Ji-Woon's Autograph", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_KillingPartChords", new AddOnsInfo("Killing Part Chords", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_LuckyBlade", new AddOnsInfo("Lucky Blade", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_MementoBlades", new AddOnsInfo("Memento Blades", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_OnTargetSingle", new AddOnsInfo("On Target Single", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_RipperBrace", new AddOnsInfo("Ripper Brace", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_SmashNrunGloves", new AddOnsInfo("Smashnrun Gloves", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_TequilaMoonrock", new AddOnsInfo("Tequila Moonrock", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_TrickBlades", new AddOnsInfo("Trick Blades", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_TrickPouch", new AddOnsInfo("Trick Pouch", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_WaitingForYouWatch", new AddOnsInfo("Waiting For You Watch", "Showstopper", "The Trickster") },
			{"Comet/icons_Addon_YumisMurder", new AddOnsInfo("Melodious Murder", "Showstopper", "The Trickster") },
			{"DLC2/iconAddon_blondeHair", new AddOnsInfo("Blond Hair", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_boyfriendsMemo", new AddOnsInfo("Boyfriend's Memo", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_deadRabbit", new AddOnsInfo("Dead Rabbit", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_glassFragment", new AddOnsInfo("Glass Fragment", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_hairBow", new AddOnsInfo("Hair Bow", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_hairBrush", new AddOnsInfo("Hair Brush", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_jMyersMemorial", new AddOnsInfo("J. Myers Memorial", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_jewelry", new AddOnsInfo("Jewellery", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_jewelryBox", new AddOnsInfo("Jewellery Box", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_judithsJournal", new AddOnsInfo("Judith's Journal", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_judithsTombstone", new AddOnsInfo("Judith's Tombstone", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_lockOfHair", new AddOnsInfo("Lock of Hair", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_memorialFlower", new AddOnsInfo("Memorial Flower", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_mirrorShard", new AddOnsInfo("Mirror Shard", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_reflectiveFragment", new AddOnsInfo("Reflective Fragment", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_scratchedMirror", new AddOnsInfo("Scratched Mirror", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_tackyEarrings", new AddOnsInfo("Tacky Earrings", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_tombstonePiece", new AddOnsInfo("Tombstone Piece", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_tuftOfHair", new AddOnsInfo("Fragrant Tuft of Hair", "Evil Within", "The Shape") },
			{"DLC2/iconAddon_vanityMirror", new AddOnsInfo("Vanity Mirror", "Evil Within", "The Shape") },
			{"DLC3/iconAddon_bloodiedMud", new AddOnsInfo("Bloodied Mud", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_bloodiedWater", new AddOnsInfo("Bloodied Water", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_bogWater", new AddOnsInfo("Bog Water", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_crackedTurtleEgg", new AddOnsInfo("Cracked Turtle Egg", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_cypressNecklet", new AddOnsInfo("Cypress Necklet", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_deadFlyMud", new AddOnsInfo("Dead Fly Mud", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_disfiguredEar", new AddOnsInfo("Disfigured Ear", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_dragonflyWings", new AddOnsInfo("Dragonfly Wings", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_driedCicada", new AddOnsInfo("Dried Cicada", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_granmasHeart", new AddOnsInfo("Granma's Heart", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_halfEggshell", new AddOnsInfo("Half Eggshell", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_mintRag", new AddOnsInfo("Mint Rag", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_powderedEggshell", new AddOnsInfo("Powdered Eggshell", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_pussyWillowCatkins", new AddOnsInfo("Pussy Willow Catkins", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_ropeNecklet", new AddOnsInfo("Rope Necklet", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_rustyShackles", new AddOnsInfo("Rusty Shackles", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_scarredHand", new AddOnsInfo("Scarred Hand", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_swampOrchidNecklet", new AddOnsInfo("Swamp Orchid Necklet", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_waterloggedShoe", new AddOnsInfo("Waterlogged Shoe", "Blackened Catalyst", "The Hag") },
			{"DLC3/iconAddon_willowWreath", new AddOnsInfo("Willow Wreath", "Blackened Catalyst", "The Hag") },
			{"DLC4/iconAddon_calmCartersNotes", new AddOnsInfo("\"Calm\" - Carter's Notes", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_calmClassI", new AddOnsInfo("\"Calm\" - Class I", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_calmClassII", new AddOnsInfo("\"Calm\" - Class II", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_diciplineCartersNotes", new AddOnsInfo("\"Discipline\" - Carter's Notes", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_diciplineClassII", new AddOnsInfo("\"Discipline\" - Class II", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_diciplineClassIII", new AddOnsInfo("\"Discipline\" - Class III", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_highStimulusElectrode", new AddOnsInfo("High Stimulus Electrode", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_interviewTape", new AddOnsInfo("Interview Tape", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_iridescentKing", new AddOnsInfo("Iridescent King", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_iridescentQueen", new AddOnsInfo("Iridescent Queen", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_mapleKnight", new AddOnsInfo("Maple Knight", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_moldyElectrode", new AddOnsInfo("Mouldy Electrode", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_obedienceCartersNotes", new AddOnsInfo("\"Obedience\" - Class III", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_orderCartersNotes", new AddOnsInfo("\"Order\" - Carter's Notes", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_orderClassI", new AddOnsInfo("\"Order\" - Class I", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_orderClassII", new AddOnsInfo("\"Order\" - Class II", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_polishedElectrode", new AddOnsInfo("Polished Electrode", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_restraintCartersNotes", new AddOnsInfo("\"Restraint\" - Carter's Notes", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_restraintClassII", new AddOnsInfo("\"Restraint\" - Class II", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_restraintClassIII", new AddOnsInfo("\"Restraint\" - Class III", "Carter's Spark", "The Doctor") },
			{"DLC4/iconAddon_scrappedTape", new AddOnsInfo("Scrapped Tape", "Carter's Spark", "The Doctor") },
			{"DLC5/iconAddon_amanitaToxin", new AddOnsInfo("Amanita Toxin", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_bandagedHaft", new AddOnsInfo("Bandaged Haft", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_begrimedHead", new AddOnsInfo("Begrimed Head", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_coarseStone", new AddOnsInfo("Coarse Stone", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_deerskinGloves", new AddOnsInfo("Deerskin Gloves", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_flowerBabushka", new AddOnsInfo("Flower Babushka", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_glowingConcoction", new AddOnsInfo("Glowing Concoction", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_infantryBelt", new AddOnsInfo("Infantry Belt", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_iridescentHead", new AddOnsInfo("Iridescent Head", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_leatherLoop", new AddOnsInfo("Leather Loop", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_mannaGrassBraid", new AddOnsInfo("Manna Grass Braid", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_oakHaft", new AddOnsInfo("Oak Haft", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_roseRoot", new AddOnsInfo("Rose Root", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_rustyHead", new AddOnsInfo("Rusty Head", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_shinyPin", new AddOnsInfo("Shiny Pin", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_soldiersPuttee", new AddOnsInfo("Soldier's Puttee", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_venomousConcoction", new AddOnsInfo("Venomous Concoction", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_weightedHead", new AddOnsInfo("Weighted Head", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_woodenFox", new AddOnsInfo("Wooden Fox", "Hunting Hatchets", "The Huntress") },
			{"DLC5/iconAddon_yellowedCloth", new AddOnsInfo("Yellowed Cloth", "Hunting Hatchets", "The Huntress") },
			{"DLC6/iconAddon_awardwinningChili", new AddOnsInfo("Award-winning Chilli", "Bubba's Chainsaw", "The Cannibal") },
			{"DLC6/iconAddon_chili", new AddOnsInfo("Chilli", "Bubba's Chainsaw", "The Cannibal") },
			{"DLC6/iconAddon_knifeScratches", new AddOnsInfo("Knife Scratches", "Bubba's Chainsaw", "The Cannibal") },
			{"DLC6/iconAddon_theBeastsMark", new AddOnsInfo("The Beast's Marks", "Bubba's Chainsaw", "The Cannibal") },
			{"DLC6/iconAddon_theGrease", new AddOnsInfo("The Grease", "Bubba's Chainsaw", "The Cannibal") },
			{"Eclipse/iconAddon_TVirusSample", new AddOnsInfo("T-Virus Sample", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_adminWristband", new AddOnsInfo("Admin Wristband", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_adrenalineInjector", new AddOnsInfo("Adrenaline Injector", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_briansIntestines", new AddOnsInfo("Brian's Intestines", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_brokenRecoveryCoin", new AddOnsInfo("Broken Recovery Coin", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_damagedSyringe", new AddOnsInfo("Damaged Syringe", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_depletedInkRibbon", new AddOnsInfo("Depleted Ink Ribbon", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_iridescentUmbrellaBadge", new AddOnsInfo("Iridescent Umbrella Badge", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_jillSandwich", new AddOnsInfo("Jill's Sandwich", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_lickerTongue", new AddOnsInfo("Licker Tongue", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_marvinsBlood", new AddOnsInfo("Marvin's Blood", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_mikhailsEye", new AddOnsInfo("Mikhail's Eye", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_neaParasite", new AddOnsInfo("NE-a Parasite", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_plant43Vines", new AddOnsInfo("Plant 43 Vines", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_serotoninInjector", new AddOnsInfo("Serotonin Injector", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_shatteredStarsBadge", new AddOnsInfo("Shattered S.T.A.R.S. Badge", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_starsFieldCombatManual", new AddOnsInfo("S.T.A.R.S. Field Combat Manual", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_tyrantGore", new AddOnsInfo("Tyrant Gore", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_visitorWristband", new AddOnsInfo("Visitor Wristband", "T-Virus", "The Nemesis") },
			{"Eclipse/iconAddon_zombieHeart", new AddOnsInfo("Zombie Heart", "T-Virus", "The Nemesis") },
			{"England/iconAddon_blackBox", new AddOnsInfo("Black Box", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_blueDress", new AddOnsInfo("Blue Dress", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_catBlock", new AddOnsInfo("Cat Block", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_classPhoto", new AddOnsInfo("Class Photo", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_gardenRake", new AddOnsInfo("Garden Rake", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_greenDress", new AddOnsInfo("Green Dress", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_jumpRope", new AddOnsInfo("Jump Rope", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_kidsDrawing", new AddOnsInfo("Kid's Drawing", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_nancysMasterpiece", new AddOnsInfo("Nancy's Masterpiece", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_nancysSketch", new AddOnsInfo("Nancy's Sketch", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_outdoorRope", new AddOnsInfo("Outdoor Rope", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_paintThinner", new AddOnsInfo("Paint Thinner", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_pillBottle", new AddOnsInfo("Pill Bottle", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_prototypeClaw", new AddOnsInfo("Prototype Claw", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_redPaintBrush", new AddOnsInfo("Red Paint Brush", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_sheepBlock", new AddOnsInfo("Sheep Block", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_swingChains", new AddOnsInfo("Swing Chains", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_unicornBlock", new AddOnsInfo("Unicorn Block", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_woolShirt", new AddOnsInfo("Wool Shirt", "Dream Demon", "The Nightmare") },
			{"England/iconAddon_zBlock", new AddOnsInfo("\"Z\" Block", "Dream Demon", "The Nightmare") },
			{"Finland/iconAddon_amandasLetter", new AddOnsInfo("Amanda's Letter", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_amandasSecret", new AddOnsInfo("Amanda's Secret", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_bagOfGears", new AddOnsInfo("Bag of Gears", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_combatStraps", new AddOnsInfo("Combat Straps", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_crateOfGears", new AddOnsInfo("Crate of Gears", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_faceMask", new AddOnsInfo("Face Mask", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_interlockingRazor", new AddOnsInfo("Interlocking Razor", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_jigsawsAnnotatedPlan", new AddOnsInfo("Jigsaw's Annotated Plan", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_jigsawsSketch", new AddOnsInfo("Jigsaw's Sketch", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_johnsMedicalFile", new AddOnsInfo("John's Medical File", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_lastWill", new AddOnsInfo("Last Will", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_razerWire", new AddOnsInfo("Razor Wires", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_rulesSetN2", new AddOnsInfo("Rules Set No.2", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_rustyAttachments", new AddOnsInfo("Rusty Attachments", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_shatteredSyringe", new AddOnsInfo("Shattered Syringe", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_slowReleaseToxin", new AddOnsInfo("Slow-Release Toxin", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_tamperedTimer", new AddOnsInfo("Tampered Timer", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_utilityBlades", new AddOnsInfo("Utility Blades", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_videoTape", new AddOnsInfo("Video Tape", "Jigsaw's Baptism", "The Pig") },
			{"Finland/iconAddon_workshopGrease", new AddOnsInfo("Workshop Grease", "Jigsaw's Baptism", "The Pig") },
			{"Gemini/iconAddon_bentNail", new AddOnsInfo("Bent Nail", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_burningCandle", new AddOnsInfo("Burning Candle", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_chatterersTooth", new AddOnsInfo("Chatterer's Tooth", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_engineersFang", new AddOnsInfo("Engineer's Fang", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_flickeringTelevision", new AddOnsInfo("Flickering Television", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_franksHeart", new AddOnsInfo("Frank's Heart", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_greasyBlackLens", new AddOnsInfo("Greasy Black Lens", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_impalingWire", new AddOnsInfo("Impaling Wire", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_iridescentLamentConfiguration", new AddOnsInfo("Iridescent Lament Configuration", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_larrysBlood", new AddOnsInfo("Larry's Blood", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_larrysRemains", new AddOnsInfo("Larry's Remains", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_leatherStrip", new AddOnsInfo("Leather Strip", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_liquifiedGore", new AddOnsInfo("Liquified Gore", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_livelyCrickets", new AddOnsInfo("Lively Crickets", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_originalPain", new AddOnsInfo("Original Pain", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_skeweredRat", new AddOnsInfo("Skewered Rat", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_sliceofFrank", new AddOnsInfo("Slice of Frank", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_spoiledMeal", new AddOnsInfo("Spoiled Meal", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_torturePillar", new AddOnsInfo("Torture Pillar", "Summons of Pain", "The Cenobite") },
			{"Gemini/iconAddon_wrigglingMaggots", new AddOnsInfo("Wriggling Maggots", "Summons of Pain", "The Cenobite") },
			{"Guam/iconAddon_bottleOfChloroform", new AddOnsInfo("Bottle of Chloroform", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_cheapGinBottle", new AddOnsInfo("Cheap Gin Bottle", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_cigarBox", new AddOnsInfo("Cigar Box", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_ether10", new AddOnsInfo("Ether 5 Vol%", "The Afterpiece Tonic", "The Clown",true) },
			{"Guam/iconAddon_ether15", new AddOnsInfo("Ether 15 Vol%", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_ether5", new AddOnsInfo("Ether 10 Vol%", "The Afterpiece Tonic", "The Clown",true) },
			{"Guam/iconAddon_fingerlessParadeGloves", new AddOnsInfo("Fingerless Parade Gloves", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_flaskOfBleach", new AddOnsInfo("Flask of Bleach", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_garishMakeupKit", new AddOnsInfo("Garish Make-Up Kit", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_keroseneCan", new AddOnsInfo("Kerosene Can", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_partyBottle", new AddOnsInfo("Party Bottle", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_redheadsPinkyFinger", new AddOnsInfo("Redhead's Pinkie Finger", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_robinFeather", new AddOnsInfo("Robin Feather", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_smellyInnerSoles", new AddOnsInfo("Smelly Inner Soles", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_solventJug", new AddOnsInfo("Solvent Jug", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_spiritOfHartshorn", new AddOnsInfo("Spirit of Hartshorn", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_starlingFeather", new AddOnsInfo("Starling Feather", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_stickySodaBottle", new AddOnsInfo("Sticky Soda Bottle", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_sulfuricAcidVial", new AddOnsInfo("Sulphuric Acid Vial", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_tattoosMiddleFinger", new AddOnsInfo("Tattoo's Middle Finger", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_thickCorkStopper", new AddOnsInfo("Thick Cork Stopper", "The Afterpiece Tonic", "The Clown") },
			{"Guam/iconAddon_vhsPorn", new AddOnsInfo("VHS Porn", "The Afterpiece Tonic", "The Clown") },
			{"Haiti/iconAddon_ShiawaseAmulet", new AddOnsInfo("Shiawase Amulet", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_driedCherryBlossom", new AddOnsInfo("Dried Cherry Blossom", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_giftedBambooComb", new AddOnsInfo("Gifted Bamboo Comb", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_juniperBonzai", new AddOnsInfo("Juniper Bonzai", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_kaiunTalisman", new AddOnsInfo("Kaiun Talisman", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_katanaTsuba", new AddOnsInfo("Katana Tsuba", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_motherDaughterRing", new AddOnsInfo("Mother-Daughter Ring", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_muddySportCap", new AddOnsInfo("Muddy Sports Day Cap", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_origamiCrane", new AddOnsInfo("Origami Crane", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_rinsBrokenWatch", new AddOnsInfo("Rin's Broken Watch", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_rustyFlute", new AddOnsInfo("Rusty Flute", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_wakizashiSaya", new AddOnsInfo("Wakizashi Saya", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_whiteHairRibbon", new AddOnsInfo("White Hair Ribbon", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_yakuyokeAmulet", new AddOnsInfo("Yakuyoke Amulet", "Yamaoka's Haunting", "The Spirit") },
			{"Haiti/iconAddon_zori", new AddOnsInfo("Zōri", "Yamaoka's Haunting", "The Spirit") },
			{"Hubble/iconAddon_furin", new AddOnsInfo("Furin", "Yamaoka's Haunting", "The Spirit") },
			{"Hubble/iconAddon_kintsugiTeacup", new AddOnsInfo("Kintsugi Teacup", "Yamaoka's Haunting", "The Spirit") },
			{"Hubble/iconAddon_mothersGlasses", new AddOnsInfo("Mother's Glasses", "Yamaoka's Haunting", "The Spirit") },
			{"Hubble/iconAddon_senkoHanabi", new AddOnsInfo("Senko Hanabi", "Yamaoka's Haunting", "The Spirit") },
			{"Hubble/iconAddon_uchiwa", new AddOnsInfo("Uchiwa", "Yamaoka's Haunting", "The Spirit") },
			{"Ion/iconAddon_AutomaticDrawing", new AddOnsInfo("Automatic Drawing", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_CharcoalStick", new AddOnsInfo("Charcoal Stick", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_ChocloCorn", new AddOnsInfo("Choclo Corn", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_DarkestInk", new AddOnsInfo("Darkest Ink", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_FesteringCarrion", new AddOnsInfo("Festering Carrion", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_GardenofRot", new AddOnsInfo("Garden of Rot", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_InkEgg", new AddOnsInfo("Ink Egg", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_IridescentFeather", new AddOnsInfo("Iridescent Feather", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_JacobsBabyShoes", new AddOnsInfo("Matias' Baby Shoes", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_OGriefOLover", new AddOnsInfo("O Grief, O Lover", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_OilPaints", new AddOnsInfo("Oil Paints", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_SeveredHands", new AddOnsInfo("Severed Hands", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_SeveredTongue", new AddOnsInfo("Severed Tongue", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_SilverBell", new AddOnsInfo("Silver Bell", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_StillLifeCrow", new AddOnsInfo("Still Life Crow", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_ThickTar", new AddOnsInfo("Thick Tar", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_ThornyNest", new AddOnsInfo("Thorny Nest", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_UntitledAgony", new AddOnsInfo("Untitled Agony", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_VelvetFabric", new AddOnsInfo("Velvet Fabric", "Birds of Torment", "The Artist") },
			{"Ion/iconAddon_VibrantObituary", new AddOnsInfo("Vibrant Obituary", "Birds of Torment", "The Artist") },
			{"Kenya/iconAddon_coldDirt", new AddOnsInfo("BFFs", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_defacedSmileyButton", new AddOnsInfo("Defaced Smiley Pin", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_etchedRuler", new AddOnsInfo("Etched Ruler", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_filthyBlade", new AddOnsInfo("Filthy Blade", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_franksMixtape", new AddOnsInfo("Frank's Mix Tape", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_friendshipBracelet", new AddOnsInfo("Friendship Bracelet", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_fumingMixtape", new AddOnsInfo("Fuming Mix Tape", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_iridescentButton", new AddOnsInfo("Iridescent Button", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_joeysMixtape", new AddOnsInfo("Joey's Mix Tape", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_juliesMixtape", new AddOnsInfo("Julie's Mix Tape", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_mischiefList", new AddOnsInfo("Mischief List", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_muralSketch", new AddOnsInfo("Mural Sketch", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_nastyBlade", new AddOnsInfo("Stylish Sunglasses", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_neverSleepPills", new AddOnsInfo("Never-Sleep Pills", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_scratchedRuler", new AddOnsInfo("Scratched Ruler", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_smileyFaceButton", new AddOnsInfo("Smiley Face Pin", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_stabWoundsStudy", new AddOnsInfo("Stab Wounds Study", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_stolenSketchbook", new AddOnsInfo("Stolen Sketch Book", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_suziesMixtape", new AddOnsInfo("Suzie's Mix Tape", "Feral Frenzy", "The Legion") },
			{"Kenya/iconAddon_theLegionButton", new AddOnsInfo("The Legion Pin", "Feral Frenzy", "The Legion") },
			{"Kepler/iconAddon_BloodyFingernail", new AddOnsInfo("Bloody Fingernails", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_CabinSign", new AddOnsInfo("Cabin Sign", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_ClumpOfHair", new AddOnsInfo("Clump of Hair", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_DisortedPhoto", new AddOnsInfo("Distorted Photo", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_IridescentVHStape", new AddOnsInfo("Iridescent Videotape", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_MothersComb", new AddOnsInfo("Mother's Comb", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_MothersMirror", new AddOnsInfo("Mother's Mirror", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_OldNewspaper", new AddOnsInfo("Old Newspaper", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_ReikosWatch", new AddOnsInfo("Reiko's Watch", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_RemoteControl", new AddOnsInfo("Remote Control", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_RicketyPinwheel", new AddOnsInfo("Rickety Pinwheel", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_RingDrawing", new AddOnsInfo("Ring Drawing", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_SeaSoakedCloth", new AddOnsInfo("Sea-Soaked Cloth", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_TapeEditingDeck", new AddOnsInfo("Tape Editing Deck", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_Telephone", new AddOnsInfo("Telephone", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_VCR", new AddOnsInfo("VCR", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_VhsCopy", new AddOnsInfo("Videotape Copy", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_WellStone", new AddOnsInfo("Well Stone", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_WellWater", new AddOnsInfo("Well Water", "Deluge of Fear", "The Onryō") },
			{"Kepler/iconAddon_YoichisFishingNet", new AddOnsInfo("Yoichi's Fishing Net", "Deluge of Fear", "The Onryō") },
			{"Mali/iconAddon_IridescentSeal", new AddOnsInfo("Iridescent Seal", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_ashenApple", new AddOnsInfo("Ashen Apple", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_blackIncense", new AddOnsInfo("Black Incense", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_devoteesAmulet", new AddOnsInfo("Devotee's Amulet", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_emeticPotion", new AddOnsInfo("Emetic Potion", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_exorcismAmulet", new AddOnsInfo("Exorcism Amulet", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_healingSalve", new AddOnsInfo("Healing Salve", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_hematiteSeal", new AddOnsInfo("Hematite Seal", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_incensedOintment", new AddOnsInfo("Incensed Ointment", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_infectedEmetic", new AddOnsInfo("Infected Emetic", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_limestoneSeal", new AddOnsInfo("Limestone Seal", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_olibanumIncense", new AddOnsInfo("Olibanum Incense", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_potentTincture", new AddOnsInfo("Potent Tincture", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_prayerApple", new AddOnsInfo("Blessed Apple", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_prayerTabletFragment", new AddOnsInfo("Prayer Tablet Fragment", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_prophylacticAmulet", new AddOnsInfo("Prophylactic Amulet", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_rubbingOil", new AddOnsInfo("Rubbing Oil", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_severedToe", new AddOnsInfo("Severed Toe", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_vileEmetic", new AddOnsInfo("Vile Emetic", "Vile Purge", "The Plague") },
			{"Mali/iconAddon_worshipTablet", new AddOnsInfo("Worship Tablet", "Vile Purge", "The Plague") },
			{"Meteor/iconAddon_AirFreshner", new AddOnsInfo("Air Freshener", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_BoatKey", new AddOnsInfo("Boat Key", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_BrokenDoll", new AddOnsInfo("Broken Doll", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_BurntLetters", new AddOnsInfo("Burnt Letters", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_CaffeineTablets", new AddOnsInfo("Caffeine Tablets", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_DestroyedPillow", new AddOnsInfo("Destroyed Pillow", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_FallenShingle", new AddOnsInfo("Fallen Shingle", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_FieldRecorder", new AddOnsInfo("Field Recorder", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_FollowersCowl", new AddOnsInfo("Follower's Cowl", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_HaddiesCalendar", new AddOnsInfo("Haddie's Calendar", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_IridescentWoodenPlank", new AddOnsInfo("Iridescent Wooden Plank", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_LavalierMicrophone", new AddOnsInfo("Lavalier Microphone", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_MalthinkersSkull", new AddOnsInfo("Malthinker's Skull", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_MortarAndPestle", new AddOnsInfo("Mortar and Pestle", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_OttomarianWriting", new AddOnsInfo("Ottomarian Writing", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_SacrificialKnife", new AddOnsInfo("Sacrificial Knife", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_TilingBlade", new AddOnsInfo("Tilling Blade", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_WarHelmet", new AddOnsInfo("War Helmet", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_WoodenPlank", new AddOnsInfo("Wooden Plank", "Reign of Darkness", "The Dredge") },
			{"Meteor/iconAddon_WorryStones", new AddOnsInfo("Worry Stone", "Reign of Darkness", "The Dredge") },
			{"Oman/iconAddon_caughtOnTape", new AddOnsInfo("\"Ghost Face Caught on Tape\"", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_cheapCologne", new AddOnsInfo("Cheap Cologne", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_chewedPen", new AddOnsInfo("Chewed Pen", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_driversLicense", new AddOnsInfo("Driver's License", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_dropLegKnifeSheath", new AddOnsInfo("Drop-Leg Knife Sheath", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_headlinesCutouts", new AddOnsInfo("Headlines Cut-Outs", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_knifeBeltClip", new AddOnsInfo("Knife Belt Clip", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_lastingPerfume", new AddOnsInfo("Lasting Perfume", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_leatherKnifeSheath", new AddOnsInfo("Leather Knife Sheath", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_markedMap", new AddOnsInfo("Marked Map", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_nightvisionMoncular", new AddOnsInfo("Night Vision Monocular", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_olsensAddressBook", new AddOnsInfo("Olsen's Address Book", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_olsensJournal", new AddOnsInfo("Olsen's Journal", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_olsensWallet", new AddOnsInfo("Olsen's Wallet", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_outdoorSecurityCamera", new AddOnsInfo("Outdoor Security Camera", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_philly", new AddOnsInfo("\"Philly\"", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_reusuableCinchStraps", new AddOnsInfo("Cinch Straps", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_telephotoLens", new AddOnsInfo("Telephoto Lens", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_victimsDetailedRoutine", new AddOnsInfo("Victim's Detailed Routine", "Night Shroud", "The Ghost Face") },
			{"Oman/iconAddon_walleyesMatchbook", new AddOnsInfo("Walleye's Matchbook", "Night Shroud", "The Ghost Face") },
			{"Qatar/iconAddon_barbsGlasses", new AddOnsInfo("Barb's Glasses", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_blackHeart", new AddOnsInfo("Black Heart", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_brassCaseLighter", new AddOnsInfo("Brass Case Lighter", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_deerLung", new AddOnsInfo("Deer Lung", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_elevensSoda", new AddOnsInfo("Eleven's Soda", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_leproseLichen", new AddOnsInfo("Leprose Lichen", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_lifeguardWhistle", new AddOnsInfo("Lifeguard Whistle", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_mewsGuts", new AddOnsInfo("Mew's Guts", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_ratLiver", new AddOnsInfo("Rat Liver", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_ratTail", new AddOnsInfo("Rat Tail", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_redMoss", new AddOnsInfo("Red Moss", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_rottenGreenTripe", new AddOnsInfo("Rotten Green Tripe", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_rottenPumpkin", new AddOnsInfo("Rotten Pumpkin", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_stickyLining", new AddOnsInfo("Sticky Lining", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_thornyVines", new AddOnsInfo("Thorny Vines", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_unknownEgg", new AddOnsInfo("Unknown Egg", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_upsidedownResin", new AddOnsInfo("Upside Down Resin", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_vermillionWebcap", new AddOnsInfo("Vermillion Webcap", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_violetWaxcap", new AddOnsInfo("Violet Waxcap", "Of the Abyss", "The Demogorgon") },
			{"Qatar/iconAddon_viscousWebbing", new AddOnsInfo("Viscous Webbing", "Of the Abyss", "The Demogorgon") },
			{"Sweden/iconAddon_IridescentFamilyCrest", new AddOnsInfo("Iridescent Family Crest", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_akitosCrutch", new AddOnsInfo("Akito's Crutch", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_blackenedToenail", new AddOnsInfo("Blackened Toenail", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_bloodySash", new AddOnsInfo("Bloody Sash", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_childsWoodenSword", new AddOnsInfo("Child's Wooden Sword", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_chippedSaihai", new AddOnsInfo("Chipped Saihai", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_crackedSakazuki", new AddOnsInfo("Cracked Sakazuki", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_inkLion", new AddOnsInfo("Ink Lion", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_kanaianzenTalisman", new AddOnsInfo("Kanai-Anzen Talisman", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_lionFang", new AddOnsInfo("Lion Fang", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_paperLantern", new AddOnsInfo("Paper Lantern", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_polishedMaedate", new AddOnsInfo("Polished Maedate", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_renirosBloodyGlove", new AddOnsInfo("Reniro's Bloody Glove", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_rottingRope", new AddOnsInfo("Rotting Rope", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_scalpedTopknot", new AddOnsInfo("Scalped Topknot", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_shatteredWakizashi", new AddOnsInfo("Shattered Wakizashi", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_splinteredHull", new AddOnsInfo("Splintered Hull", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_tearSoakedTenugui", new AddOnsInfo("Tear Soaked Tenugui", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_woodenOniMask", new AddOnsInfo("Wooden Oni Mask", "Yamaoka's Wrath", "The Oni") },
			{"Sweden/iconAddon_yamaokaSashimono", new AddOnsInfo("Yamaoka Sashimono", "Yamaoka's Wrath", "The Oni") },
			{"Ukraine/iconAddon_barbedWire", new AddOnsInfo("Barbed Wire", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_bayshoresCigar", new AddOnsInfo("Bayshore's Cigar", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_bayshoresGoldTooth", new AddOnsInfo("Bayshore's Gold Tooth", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_chewingTobacco", new AddOnsInfo("Chewing Tobacco", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_clearCreekWhiskey", new AddOnsInfo("Gold Creek Whiskey", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_hellshireIron", new AddOnsInfo("Hellshire Iron", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_honeyLocustThorns", new AddOnsInfo("Honey Locust Thorns", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_iridescentCoin", new AddOnsInfo("Iridescent Coin", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_jawSmasher", new AddOnsInfo("Jaw Smasher", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_marshalsBadge", new AddOnsInfo("Marshal's Badge", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_modifiedAmmoBelt", new AddOnsInfo("Modified Ammo Belt", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_poisonOakLeaves", new AddOnsInfo("Poison Oak Leaves", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_prisonChain", new AddOnsInfo("Prison Chain", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_ricketyChain", new AddOnsInfo("Rickety Chain", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_rustedSpike", new AddOnsInfo("Rusted Spike", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_snakeOil", new AddOnsInfo("Snake Oil", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_spitPolishRag", new AddOnsInfo("Spit Polish Rag", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_tinOilCan", new AddOnsInfo("Tin Oil Can", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_wantedPoster", new AddOnsInfo("Wanted Poster", "The Redeemer", "The Deathslinger") },
			{"Ukraine/iconAddon_wardensKeys", new AddOnsInfo("Warden's Keys", "The Redeemer", "The Deathslinger") },
			{"Wales/iconAddon_blackStrap", new AddOnsInfo("Black Strap", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_burningManPainting", new AddOnsInfo("Burning Man Painting", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_cinderellaMusicBox", new AddOnsInfo("Cinderella Music Box", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_copperRing", new AddOnsInfo("Copper Ring", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_crimsonCeremonyBook", new AddOnsInfo("Crimson Ceremony Book", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_deadButterfly", new AddOnsInfo("Dead Butterfly", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_forgottenVideoTape", new AddOnsInfo("Forgotten Videotape", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_iridescentSeal", new AddOnsInfo("Iridescent Seal of Metatron", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_leadRing", new AddOnsInfo("Lead Ring", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_leopardPrintFabric", new AddOnsInfo("Leopard-Print Fabric", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_lostMemoriesBook", new AddOnsInfo("Lost Memories Book", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_mannequinFoot", new AddOnsInfo("Mannequin Foot", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_mistyDay", new AddOnsInfo("Misty Day, Remains of Judgement", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_obsidianGoblet", new AddOnsInfo("Obsidian Goblet", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_rustColoredEgg", new AddOnsInfo("Rust-Coloured Egg", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_scarletEgg", new AddOnsInfo("Scarlet Egg", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_spearhead", new AddOnsInfo("Spearhead", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_tabletOfTheOppressor", new AddOnsInfo("Tablet of the Oppressor", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_valtielSectPhotograph", new AddOnsInfo("Valtiel Sect Photograph", "Rites of Judgement", "The Executioner") },
			{"Wales/iconAddon_waxDoll", new AddOnsInfo("Wax Doll", "Rites of Judgement", "The Executioner") },
			{"Xipre/iconAddon_apexMuffler", new AddOnsInfo("Apex Muffler", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_bigBuckle", new AddOnsInfo("Big Buckle", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_blackGrease", new AddOnsInfo("Black Grease", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_dadsBoots", new AddOnsInfo("Dad's Boots", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_deathEngravings", new AddOnsInfo("Death Engravings", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_doomEngravings", new AddOnsInfo("Doom Engravings", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_heavyClutch", new AddOnsInfo("Heavy Clutch", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_iridescentBrick", new AddOnsInfo("Iridescent Brick", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_junkyardAirFilter", new AddOnsInfo("Junkyard Air Filter", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_leafyMash", new AddOnsInfo("Leafy Mash", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_lowKickbackChains", new AddOnsInfo("Low Kickback Chains", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_lowProChains", new AddOnsInfo("LoPro Chains", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_mothersHelpers", new AddOnsInfo("Mother's Helpers", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_offBrandMotorOil", new AddOnsInfo("Off-Brand Motor Oil", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_pighouseGloves", new AddOnsInfo("Pighouse Gloves", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_puncturedMuffler", new AddOnsInfo("Punctured Muffler", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_speedLimiter", new AddOnsInfo("Speed Limiter", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_spikedBoots", new AddOnsInfo("Spiked Boots", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_steelToeBoots", new AddOnsInfo("Steel Toe Boots", "Chainsaw", "The Hillbilly") },
			{"Xipre/iconAddon_tunedCarburetor", new AddOnsInfo("Tuned Carburettor", "Chainsaw", "The Hillbilly") },
			{"Yemen/iconAddon_adrenalineVial", new AddOnsInfo("Adrenaline Vial", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_alchemistsRing", new AddOnsInfo("Alchemist's Ring", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_blightedCrow", new AddOnsInfo("Blighted Crow", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_blightedRat", new AddOnsInfo("Blighted Rat", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_cankerThorn", new AddOnsInfo("Canker Thorn", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_chippedMonocle", new AddOnsInfo("Chipped Monocle", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_compoundSeven", new AddOnsInfo("Compound Seven", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_compoundThirtyThree", new AddOnsInfo("Compound Thirty-Three", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_compoundTwentyOne", new AddOnsInfo("Compound Twenty-One", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_foxglove", new AddOnsInfo("Foxglove", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_iridescentBlightTag", new AddOnsInfo("Iridescent Blight Tag", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_placeboTablet", new AddOnsInfo("Placebo Tablet", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_plagueBile", new AddOnsInfo("Plague Bile", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_pustulaDust", new AddOnsInfo("Pustula Dust", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_roseTonic", new AddOnsInfo("Rose Tonic", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_shreddedNotes", new AddOnsInfo("Shredded Notes", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_soulChemical", new AddOnsInfo("Soul Chemical", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_summoningStone", new AddOnsInfo("Summoning Stone", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_umbraSalts", new AddOnsInfo("Umbra Salts", "Blighted Corruption", "The Blight") },
			{"Yemen/iconAddon_vigosJournal", new AddOnsInfo("Vigo's Journal", "Blighted Corruption", "The Blight") },
			{"iconAddon_anxiousGasp", new AddOnsInfo("Anxious Gasp", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_ataxicRespiration", new AddOnsInfo("Ataxic Respiration", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_badManKeepsake", new AddOnsInfo("Bad Man Keepsake", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_badMansLastBreath", new AddOnsInfo("\"Badman's\" Last Breath", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_bearOil", new AddOnsInfo("Bear Oil", "Bear Trap", "The Trapper") },
			{"iconAddon_bloodKraFabai", new AddOnsInfo("\"All Seeing\" - Blood", "Wailing Bell", "The Wraith") },
			{"iconAddon_bloodShadowDance", new AddOnsInfo("\"Shadow Dance\" - Blood", "Wailing Bell", "The Wraith") },
			{"iconAddon_bloodSwiftHunt", new AddOnsInfo("\"Swift Hunt\" - Blood", "Wailing Bell", "The Wraith") },
			{"iconAddon_bloodWindstorm", new AddOnsInfo("\"Windstorm\" - Blood", "Wailing Bell", "The Wraith") },
			{"iconAddon_bloodyCoil", new AddOnsInfo("Bloody Coil", "Bear Trap", "The Trapper") },
			{"iconAddon_boneClapper", new AddOnsInfo("Bone Clapper", "Wailing Bell", "The Wraith") },
			{"iconAddon_campbellsLastBreath", new AddOnsInfo("Campbell's Last Breath", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_carburetorTuningGuide", new AddOnsInfo("Carburetor Tuning Guide", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_catatonicTreasure", new AddOnsInfo("Catatonic Boy's Treasure", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_chainsBloody", new AddOnsInfo("Begrimed Chains", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_chainsGrisly", new AddOnsInfo("Grisly Chains", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_chainsRusted", new AddOnsInfo("Rusted Chains", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_chainsawFile", new AddOnsInfo("Chainsaw File", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_coffeeGrinds", new AddOnsInfo("Coffee Grounds", "Bear Trap", "The Trapper") },
			{"iconAddon_coilsKit4", new AddOnsInfo("4-Coil Spring Kit", "Bear Trap", "The Trapper") },
			{"iconAddon_coxcombedClapper", new AddOnsInfo("Coxcombed Clapper", "Wailing Bell", "The Wraith") },
			{"iconAddon_darkCincture", new AddOnsInfo("Dark Cincture", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_deathEngravings", new AddOnsInfo("Death Engravings", "Chainsaw", "The Hillbilly") },
			{"iconAddon_depthGaugeRake", new AddOnsInfo("Depth Gauge Rake", "Bubba's Chainsaw", "The Hillbilly") },
			{"iconAddon_diamondStone", new AddOnsInfo("Iridescent Stone", "Bear Trap", "The Trapper") },
			{"iconAddon_doomEngravings", new AddOnsInfo("Doom Engravings", "Chainsaw", "The Hillbilly") },
			{"iconAddon_dullBracelet", new AddOnsInfo("Dull Bracelet", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_fasteningTools", new AddOnsInfo("Fastening Tools", "Bear Trap", "The Trapper") },
			{"iconAddon_fragileWheeze", new AddOnsInfo("Fragile Wheeze", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_heavyPanting", new AddOnsInfo("Heavy Panting", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_homemadeMuffler", new AddOnsInfo("Homemade Muffler", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_honingStone", new AddOnsInfo("Honing Stone", "Bear Trap", "The Trapper") },
			{"iconAddon_jennersLastBreath", new AddOnsInfo("Jenner's Last Breath", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_kavanaghsLastBreath", new AddOnsInfo("Kavanagh's Last Breath", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_lengthenedJaws", new AddOnsInfo("Lengthened Jaws", "Bear Trap", "The Trapper") },
			{"iconAddon_lightChassis", new AddOnsInfo("Light Chassis", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_longGuideBar", new AddOnsInfo("Long Guide Bar", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_makeshiftWrap", new AddOnsInfo("Makeshift Wrap", "Bear Trap", "The Trapper") },
			{"iconAddon_matchBox", new AddOnsInfo("Matchbox", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_metalSpoon", new AddOnsInfo("Metal Spoon", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_mudBaikraKaeug", new AddOnsInfo("\"Blind Warrior\" - Mud", "Wailing Bell", "The Wraith") },
			{"iconAddon_mudBlink", new AddOnsInfo("\"Blink\" - Mud", "Wailing Bell", "The Wraith") },
			{"iconAddon_mudSwiftHunt", new AddOnsInfo("\"Swift Hunt\" - Mud", "Wailing Bell", "The Wraith") },
			{"iconAddon_mudWindstorm", new AddOnsInfo("\"Windstorm\" - Mud", "Wailing Bell", "The Wraith") },
			{"iconAddon_oilyCoil", new AddOnsInfo("Oily Coil", "Bear Trap", "The Trapper") },
			{"iconAddon_paddedJaws", new AddOnsInfo("Padded Jaws", "Bear Trap", "The Trapper") },
			{"iconAddon_plaidFlannel", new AddOnsInfo("Plaid Flannel", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_pocketWatch", new AddOnsInfo("Pocket Watch", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_primerBulb", new AddOnsInfo("Primer Bulb", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_rustedJaws", new AddOnsInfo("Rusted Jaws", "Bear Trap", "The Trapper") },
			{"iconAddon_secondaryCoil", new AddOnsInfo("Secondary Coil", "Bear Trap", "The Trapper") },
			{"iconAddon_serratedJaws", new AddOnsInfo("Serrated Jaws", "Bear Trap", "The Trapper") },
			{"iconAddon_shopLubricant", new AddOnsInfo("Shop Lubricant", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_sootShadowDance", new AddOnsInfo("\"Shadow Dance\" - Blood", "Wailing Bell", "The Wraith") },
			{"iconAddon_sootTheBeast", new AddOnsInfo("\"The Beast\" - Soot", "Wailing Bell", "The Wraith") },
			{"iconAddon_sootTheGhost", new AddOnsInfo("\"The Ghost\" - Soot", "Wailing Bell", "The Wraith") },
			{"iconAddon_sootTheHound", new AddOnsInfo("\"The Hound\" - Soot", "Wailing Bell", "The Wraith") },
			{"iconAddon_sootTheSerpent", new AddOnsInfo("\"The Serpent\" - Soot", "Wailing Bell", "The Wraith") },
			{"iconAddon_sparkPlug", new AddOnsInfo("Spark Plug", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_spasmodicBreath", new AddOnsInfo("Spasmodic Breath", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_speedLimiter", new AddOnsInfo("Speed Limiter", "Chainsaw", "The Hillbilly") },
			{"iconAddon_spikedBoots", new AddOnsInfo("Spiked Boots", "Chainsaw", "The Hillbilly") },
			{"iconAddon_spiritAllSeeing", new AddOnsInfo("\"All Seeing\" - Spirit", "Wailing Bell", "The Wraith") },
			{"iconAddon_tarBottle", new AddOnsInfo("Tar Bottle", "Bear Trap", "The Trapper") },
			{"iconAddon_tensionSpring", new AddOnsInfo("Tension Spring", "Bear Trap", "The Trapper") },
			{"iconAddon_theThompsonsMix", new AddOnsInfo("The Thompson's Mix", "Chainsaw", "The Hillbilly",true) },
			{"iconAddon_thompsonsMoonshine", new AddOnsInfo("Thompson's Moonshine", "Chainsaw", "The Hillbilly",true) },
			{"iconAddon_tornBookmark", new AddOnsInfo("Torn Bookmark", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_trapperBag", new AddOnsInfo("Trapper Bag", "Bear Trap", "The Trapper") },
			{"iconAddon_trapperGloves", new AddOnsInfo("Trapper Gloves", "Bear Trap", "The Trapper") },
			{"iconAddon_trapperSack", new AddOnsInfo("Trapper Sack", "Bear Trap", "The Trapper") },
			{"iconAddon_vegetableOil", new AddOnsInfo("Vegetable Oil", "Bubba's Chainsaw", "The Cannibal") },
			{"iconAddon_waxBrick", new AddOnsInfo("Wax Brick", "Bear Trap", "The Trapper") },
			{"iconAddon_whiteBlindWarrior", new AddOnsInfo("\"Blind Warrior\" - White", "Wailing Bell", "The Wraith") },
			{"iconAddon_whiteBlink", new AddOnsInfo("\"Blink\" - White", "Wailing Bell", "The Wraith") },
			{"iconAddon_whiteKuntinTakkho", new AddOnsInfo("\"Swift Hunt\" - White", "Wailing Bell", "The Wraith") },
			{"iconAddon_whiteNitComb", new AddOnsInfo("White Nit Comb", "Spencer's Last Breath", "The Nurse") },
			{"iconAddon_whiteShadowDance", new AddOnsInfo("\"Shadow Dance\" - White", "Wailing Bell", "The Wraith") },
			{"iconAddon_whiteWindstorm", new AddOnsInfo("\"Windstorm\" - White", "Wailing Bell", "The Wraith") },
			{"iconAddon_woodenHorse", new AddOnsInfo("Wooden Horse", "Spencer's Last Breath", "The Nurse") }
		};

		public static IItemInfo? GetItemAddonsInfo(string path)
        {
			if (survivorItemAddonsInfo.ContainsKey(path.
				Split("/\\".ToCharArray(), StringSplitOptions.RemoveEmptyEntries)
				.Last()))
				return survivorItemAddonsInfo[path];
			else if (killerItemAddonsInfo.ContainsKey(path))
				return killerItemAddonsInfo[path];
			return null;
        }
    }

    public interface IItemInfo
    {
        string? Name { get; set; }
    }

    public class PerkInfo : IItemInfo
    {
        public PerkInfo(string? name, string? owner)
        {
            Name = name;
            if (owner is not null)
                PerkOwner = owner;
        }

        public string? Name { get; set; }

        public string? PerkOwner { get; init; }
    }

    public class KillerPowerInfo : IItemInfo
    {
		public KillerPowerInfo(string? name, string? owner)
        {
			Name = name;
			if (owner is not null)
				PowerOwner = owner;
        }

		public string? Name { get; set; }
		public string? PowerOwner { get; set; }
    }

    public class AddOnsInfo : IItemInfo
    {
		public AddOnsInfo(string? name, string? forItem)
        {
			Name = name;
			For = forItem;
			Owner = null;
        }

		public AddOnsInfo(string? name, string? forPower, string? owner, bool isDecommissioned = false)
        {
			Name = name;
			For = forPower;
			Owner = owner;
			IsDecommissioned = isDecommissioned;
        }

		public string? Name { get; set; }
		public string? For { get; set; }
		public string? Owner { get; set; }

		public bool IsDecommissioned { get; set; } = false;
    }
}
