namespace DBDIconRepo.Model
{
    public class MessageToken
    {
        public const string FILTEROPTIONSCHANGETOKEN = "FILTEROPTIONCHANGED";
        public const string SETTINGVALUECHANGETOKEN = "SETTINGVALUECHANGED";
        public const string REQUESTSEARCHQUERYTOKEN = "REQUESTEDSEARCHQUERY";
        public const string REQUESTDOWNLOADREPOTOKEN = "REQUESTEDDOWNLOADREPO";
        public const string REPOSITORYDOWNLOADREPORTTOKEN = "REPOSITORYDOWNLOADING";
        public const string REQUESTVIEWPACKDETAIL = "OPENNINGPACKDETAILWINDOWNOW";
        public const string REPOWAITFORINSTALLTOKEN = "REPOWAITINGFORINSTALL";
        public const string REPORTINSTALLPACKTOKEN = "REPORTINSTALLINGPACK";
    }
}
